# -*- coding: utf-8 -*-
"""election_sentiment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Lqtghr8o7-srIRs4nududk3A6HcF8--
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

modi=pd.read_csv('modi_reviews.csv')
rahul=pd.read_csv('rahul_reviews.csv')

modi.head()

rahul.head()

rahul['Tweet']=rahul['Tweet'].astype(str)
modi['Tweet']=modi['Tweet'].astype(str)

pip install textblob

from textblob import TextBlob

rahul.shape

TextBlob(rahul['Tweet'][0]).sentiment

def find_polarity(text):
  return TextBlob(text).sentiment.polarity

modi['polarity']=modi['Tweet'].apply(find_polarity)

modi.head()

rahul.head()

modi=modi[modi['polarity']!=0]
rahul=rahul[rahul['polarity']!=0]

rahul.shape

modi.shape

np.random.seed(10)
remove_n = 8481
drop_indices = np.random.choice(modi.index,remove_n,replace=False)
df_modi = modi.drop(drop_indices)

np.random.seed(10)
remove_n = 367
drop_indices = np.random.choice(rahul.index,remove_n,replace=False)
df_rahul =rahul.drop(drop_indices)

df_modi.shape

df_rahul.shape

df_rahul['label'] = df_rahul['polarity'].apply(lambda x: 'positive' if x > 0 else 'negative')
df_modi['label'] = df_modi['polarity'].apply(lambda x: 'positive' if x > 0 else 'negative')

df_rahul

df_modi

df_rahul.groupby('label').count()

modi_count=df_modi.groupby('label').count()
rahul_count=df_rahul.groupby('label').count()

modi_neg=modi_count['polarity'][0]
modi_pos=modi_count['polarity'][1]
rahul_neg=rahul_count['polarity'][0]
rahul_pos=rahul_count['polarity'][1]

print("positive reviews of modi ",modi_pos)
print("negative reviews of modi ",modi_neg)
print("positive reviews of modi ",rahul_pos)
print("negative reviews of modi ",rahul_neg)

categories = ['Positive', 'Negative']
modi_reviews = [modi_pos, modi_neg]
rahul_reviews = [rahul_pos, rahul_neg]

# Create the figure and axis objects
fig, ax = plt.subplots()

# Width of the bars
bar_width = 0.35

# X-axis positions
index = np.arange(len(categories))

# Plotting Modi and Rahul's data side by side
bar1 = ax.bar(index, modi_reviews, bar_width, label='Modi')
bar2 = ax.bar(index + bar_width, rahul_reviews, bar_width, label='Rahul')

# Adding labels and title
ax.set_xlabel('Review Sentiment')
ax.set_ylabel('Number of Reviews')
ax.set_title('Comparison of Positive and Negative Reviews for Modi and Rahul')
ax.set_xticks(index + bar_width / 2)
ax.set_xticklabels(categories)
ax.legend()

# Display the chart
plt.show()